name: face_locker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  camera_windows: ^0.2.1+8
  flutter:
    sdk: flutter
  flutter_screen_lock: ^9.0.1
  local_auth: ^2.1.7
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  win32: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true